language: node_js
node_js:
  - iojs-v1.0.2
before_install:
  - "npm install -g tidy-html"
install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386 | yes